# This file configures the Dart analyzer for 2026 standards.
# It uses lints 6.0.0 and enforces strict visibility for @visibleForTesting.

include: package:lints/recommended.yaml

analyzer:
  # Enable language features available in Dart 3.8+ (expected 2026 SDK)
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Elevates @visibleForTesting violations from a hint to a hard error.
    # Code will now fail to compile if these methods are called outside tests.
    invalid_use_of_visible_for_testing_member: error
    
    # Optional: Encourage modern documentation by making missing docs an error
    public_member_api_docs: error

linter:
  rules:
    # 2026 Recommended Additions (Beyond lints 6.0.0 defaults)
    - unawaited_futures
    - avoid_final_parameters
    - use_super_parameters
    - unnecessary_library_name
